/*
 *  This file is automatically generated: do not modify
 *  ircd-ratbox: A slightly useful ircd
 *
 *  Copyright (C) 2003,2008 Aaron Sethman <androsyn@ratbox.org>
 *  Copyright (C) 2003-2005,2008 ircd-ratbox development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 *  USA
 *  
 */
#include "stdinc.h"
#include "struct.h"
#include "modules.h"
#include "hash.h"
#include "s_log.h"

extern struct mapi_header_av1 m_accept_rb_mheader;
extern struct mapi_header_av1 m_admin_rb_mheader;
extern struct mapi_header_av1 m_adminwall_rb_mheader;
extern struct mapi_header_av1 m_away_rb_mheader;
extern struct mapi_header_av1 m_capab_rb_mheader;
extern struct mapi_header_av1 m_cap_rb_mheader;
extern struct mapi_header_av1 m_close_rb_mheader;
extern struct mapi_header_av1 m_cmessage_rb_mheader;
extern struct mapi_header_av1 m_connect_rb_mheader;
extern struct mapi_header_av1 m_dline_rb_mheader;
extern struct mapi_header_av1 m_encap_rb_mheader;
extern struct mapi_header_av1 m_gline_rb_mheader;
extern struct mapi_header_av1 m_gungline_rb_mheader;
extern struct mapi_header_av1 m_help_rb_mheader;
extern struct mapi_header_av1 m_info_rb_mheader;
extern struct mapi_header_av1 m_invite_rb_mheader;
extern struct mapi_header_av1 m_ison_rb_mheader;
extern struct mapi_header_av1 m_kline_rb_mheader;
extern struct mapi_header_av1 m_knock_rb_mheader;
extern struct mapi_header_av1 m_links_rb_mheader;
extern struct mapi_header_av1 m_list_rb_mheader;
extern struct mapi_header_av1 m_locops_rb_mheader;
extern struct mapi_header_av1 m_lusers_rb_mheader;
extern struct mapi_header_av1 m_map_rb_mheader;
extern struct mapi_header_av1 m_monitor_rb_mheader;
extern struct mapi_header_av1 m_motd_rb_mheader;
extern struct mapi_header_av1 m_names_rb_mheader;
extern struct mapi_header_av1 m_oper_rb_mheader;
extern struct mapi_header_av1 m_operspy_rb_mheader;
extern struct mapi_header_av1 m_pass_rb_mheader;
extern struct mapi_header_av1 m_ping_rb_mheader;
extern struct mapi_header_av1 m_pong_rb_mheader;
extern struct mapi_header_av1 m_post_rb_mheader;
extern struct mapi_header_av1 m_rehash_rb_mheader;
extern struct mapi_header_av1 m_restart_rb_mheader;
extern struct mapi_header_av1 m_resv_rb_mheader;
extern struct mapi_header_av1 m_set_rb_mheader;
extern struct mapi_header_av1 m_stats_rb_mheader;
extern struct mapi_header_av1 m_svinfo_rb_mheader;
extern struct mapi_header_av1 m_tb_rb_mheader;
extern struct mapi_header_av1 m_testline_rb_mheader;
extern struct mapi_header_av1 m_testmask_rb_mheader;
extern struct mapi_header_av1 m_time_rb_mheader;
extern struct mapi_header_av1 m_topic_rb_mheader;
extern struct mapi_header_av1 m_trace_rb_mheader;
extern struct mapi_header_av1 m_unreject_rb_mheader;
extern struct mapi_header_av1 m_user_rb_mheader;
extern struct mapi_header_av1 m_userhost_rb_mheader;
extern struct mapi_header_av1 m_version_rb_mheader;
extern struct mapi_header_av1 m_wallops_rb_mheader;
extern struct mapi_header_av1 m_who_rb_mheader;
extern struct mapi_header_av1 m_whois_rb_mheader;
extern struct mapi_header_av1 m_whowas_rb_mheader;
extern struct mapi_header_av1 m_xline_rb_mheader;
extern struct mapi_header_av1 m_die_rb_mheader;
extern struct mapi_header_av1 m_error_rb_mheader;
extern struct mapi_header_av1 m_join_rb_mheader;
extern struct mapi_header_av1 m_kick_rb_mheader;
extern struct mapi_header_av1 m_kill_rb_mheader;
extern struct mapi_header_av1 m_message_rb_mheader;
extern struct mapi_header_av1 m_mode_rb_mheader;
extern struct mapi_header_av1 m_nick_rb_mheader;
extern struct mapi_header_av1 m_part_rb_mheader;
extern struct mapi_header_av1 m_quit_rb_mheader;
extern struct mapi_header_av1 m_server_rb_mheader;
extern struct mapi_header_av1 m_squit_rb_mheader;
const struct mapi_header_av1 *static_mapi_headers[] = {
&m_accept_rb_mheader,
&m_admin_rb_mheader,
&m_adminwall_rb_mheader,
&m_away_rb_mheader,
&m_capab_rb_mheader,
&m_cap_rb_mheader,
&m_close_rb_mheader,
&m_cmessage_rb_mheader,
&m_connect_rb_mheader,
&m_dline_rb_mheader,
&m_encap_rb_mheader,
&m_gline_rb_mheader,
&m_gungline_rb_mheader,
&m_help_rb_mheader,
&m_info_rb_mheader,
&m_invite_rb_mheader,
&m_ison_rb_mheader,
&m_kline_rb_mheader,
&m_knock_rb_mheader,
&m_links_rb_mheader,
&m_list_rb_mheader,
&m_locops_rb_mheader,
&m_lusers_rb_mheader,
&m_map_rb_mheader,
&m_monitor_rb_mheader,
&m_motd_rb_mheader,
&m_names_rb_mheader,
&m_oper_rb_mheader,
&m_operspy_rb_mheader,
&m_pass_rb_mheader,
&m_ping_rb_mheader,
&m_pong_rb_mheader,
&m_post_rb_mheader,
&m_rehash_rb_mheader,
&m_restart_rb_mheader,
&m_resv_rb_mheader,
&m_set_rb_mheader,
&m_stats_rb_mheader,
&m_svinfo_rb_mheader,
&m_tb_rb_mheader,
&m_testline_rb_mheader,
&m_testmask_rb_mheader,
&m_time_rb_mheader,
&m_topic_rb_mheader,
&m_trace_rb_mheader,
&m_unreject_rb_mheader,
&m_user_rb_mheader,
&m_userhost_rb_mheader,
&m_version_rb_mheader,
&m_wallops_rb_mheader,
&m_who_rb_mheader,
&m_whois_rb_mheader,
&m_whowas_rb_mheader,
&m_xline_rb_mheader,
&m_die_rb_mheader,
&m_error_rb_mheader,
&m_join_rb_mheader,
&m_kick_rb_mheader,
&m_kill_rb_mheader,
&m_message_rb_mheader,
&m_mode_rb_mheader,
&m_nick_rb_mheader,
&m_part_rb_mheader,
&m_quit_rb_mheader,
&m_server_rb_mheader,
&m_squit_rb_mheader,
NULL };

